name: aiu-tasks
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - cudatoolkit=10.1
  - deap
  - h5py
  - hdf5
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - pillow
  - pytorch
  - requests
  - seaborn
  - scipy
  - scikit-learn
  - scikit-image
  - statsmodels
  - torchvision
  - xlsxwriter
  - pip
  - pip:
      - gdown
      - tensorflow >= 2.0.0
      - tensorboard
      - tqdm
